[project]
name = "aoc2022"
version = "0.0.1"
description = "advent of code 2022"
requires-python = ">= 3.11"

dependencies = [
    "click", "requests"
]


[project.optional-dependencies]
dev = ["black", "isort", "ipython"]

[tool.isort]
profile = "black"